AWSTemplateFormatVersion: "2010-09-09"
Description: Endgame Viable 2024 Next.js AWS Resources

Resources:

  # S3 bucket to hold build artifacts.
  # Only used during build processes.
  artifactBucket:
    Type: AWS::S3::Bucket

  # S3 bucket containing user markdown content files.
  # This bucket is rebuilt when new content is published.
  markdownBucket:
    Type: AWS::S3::Bucket

  # S3 bucket for generated json data files.
  # This bucket is rebuilt when new content is published.
  jsonBucket:
    Type: AWS::S3::Bucket

  # SNS topic for notifications about the build process.
  buildTopic:
    Type: AWS::SNS::Topic

  # SNS email subscription for the build topic.
  # Sends me emails so I know when the build is finished.
  buildSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn:
        Ref: buildTopic
      Protocol: email
      Endpoint: endgameviable@gmail.com

  # SQS queue for events
  eventQueue:
    Type: AWS::SQS::Queue

  # DynamoDB table for generated searchable content
  searchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pagePath
          AttributeType: S
      KeySchema:
        - AttributeName: pagePath
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  stateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pagePath
          AttributeType: S
      KeySchema:
        - AttributeName: pagePath
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Role to access resources at runtime
  frontEndRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      
  # Policies to access above resources at runtime
  frontEndAccess:
    Type: "AWS::IAM::RolePolicy"
    Properties:
      RoleName: !Ref frontEndRole
      PolicyName: EndgameViableFrontendPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "s3:Get*"
            Resource: !GetAtt markdownBucket.Arn
          - Effect: "Allow"
            Action: "s3:List*"
            Resource: !GetAtt markdownBucket.Arn
          - Effect: "Allow"
            Action: "s3:Get*"
            Resource: !GetAtt jsonBucket.Arn
          - Effect: "Allow"
            Action: "s3:List*"
            Resource: !GetAtt jsonBucket.Arn
          - Effect: "Allow"
            Action: "dynamodb:Scan"
            Resource: !GetAtt searchTable.Arn
          - Effect: "Allow"
            Action: "sqs:SendMessage"
            Resource: !GetAtt eventQueue.Arn
  
  # Role to access resources at build time
  buildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow EC2 to assume this role
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
          # Allow CodePipeline to assume this role
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
          # Allow CodeBuild to assume this role
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole

  # Policies to for buildRole to access resources
  buildAccess:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName:
        Ref: buildRole
      PolicyName: endgameViableBuildAccessPolicies
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow CodeCommit to access repos
          - Effect: Allow
            # Giving up and allowing everything.
            # So tedious to fine tune permissions by trial and error.
            Action: codecommit:*
            # Content repo ARN stored in AWS Secrets Manager
            Resource:
              Fn::Sub: '{{resolve:secretsmanager:endgameviable2024-content-repo:SecretString:arn}}'
          # Allow CodeBuild to write CloudWatch logs
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*            
          # Allows CodePipeline to start the builds
          - Effect: Allow
            Action:
              - codebuild:StartBuild
              - codebuild:BatchGetBuilds
            Resource:
              - Fn::GetAtt:
                  - buildMarkdown
                  - Arn
              - Fn::GetAtt:
                  - buildJson
                  - Arn
              - Fn::GetAtt:
                  - buildDatabase
                  - Arn
          # Allow CodePipeline to use the S3 buckets.
          # Arg tired of trying to find the exact permissions
          # used by CodePipeline, just allowing everything.
          - Effect: Allow
            Action: s3:*
            Resource:
              - Fn::GetAtt:
                  - artifactBucket
                  - Arn
              - Fn::GetAtt:
                  - markdownBucket
                  - Arn
              - Fn::GetAtt:
                  - jsonBucket
                  - Arn
              - Fn::Sub: arn:aws:s3:::${artifactBucket}/*
              - Fn::Sub: arn:aws:s3:::${markdownBucket}/*
              - Fn::Sub: arn:aws:s3:::${jsonBucket}/*
          - Effect: Allow
            Action:
              - dynamodb:Write*
              - dynamodb:BatchWrite*
            Resource:
              - Fn::GetAtt:
                  - searchTable
                  - Arn
              - Fn::GetAtt:
                  - stateTable
                  - Arn
          - Effect: Allow
            Action: sqs:SendMessage
            Resource:
              Fn::GetAtt:
                - eventQueue
                - Arn

  buildTopicAccessPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - Ref: buildTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codestar-notifications.amazonaws.com
            Action: sns:Publish
            Resource:
              Ref: buildTopic

  buildPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
          - buildRole
          - Arn
      ArtifactStore:
        Type: S3
        Location:
          Ref: artifactBucket
      # Weirdly we have to fetch the source repos
      # in the Pipeline stages, even though we've
      # configured each build project to pull from
      # the right source repo. Ugh.
      # Have to be careful that the right source
      # repo goes with the right build stage.
      Stages:
        - Name: GetSource
          Actions:
            - Name: GetMarkdownRepo
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: endgameviable-content
                BranchName: main
              OutputArtifacts:
                - Name: SourceMarkdownOutput
            - Name: GetJSONRepo
              RunOrder: 2
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                # Pain in the butt to access github
                # in CodePipeline
                Owner: endgameviable
                Repo: endgameviable-json
                Branch: main
                # GitHub Personal Access Token in Secrets Manager
                OAuthToken:
                  Fn::Sub: '{{resolve:secretsmanager:endgameviable2024-github:SecretString:token}}'
              OutputArtifacts:
                - Name: SourceJsonOutput
            - Name: GetDBSyncRepo
              RunOrder: 3
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: endgameviable
                Repo: endgameviable-dbsync
                Branch: main
                OAuthToken:
                  Fn::Sub: '{{resolve:secretsmanager:endgameviable2024-github:SecretString:token}}'
              OutputArtifacts:
                - Name: SourceDBSyncOutput
        - Name: CopyMarkdownToS3
          Actions:
            - Name: BuildAction
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceMarkdownOutput
              Configuration:
                ProjectName:
                  Ref: buildMarkdown
        - Name: HugoBuildJSON
          Actions:
            - Name: BuildAction
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceJsonOutput
              Configuration:
                ProjectName:
                  Ref: buildJson
        - Name: SyncDatabase
          Actions:
            - Name: BuildAction
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceDBSyncOutput
              Configuration:
                ProjectName:
                  Ref: buildDatabase

  buildMarkdown:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole:
        Fn::GetAtt:
          - buildRole
          - Arn
      Artifacts:
        Type: S3
        Location:
          Ref: artifactBucket
      Environment:
        Type: ARM_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        EnvironmentVariables:
          - Name: S3_BUCKET_NAME
            Value:
              Ref: markdownBucket
      Source:
        Type: CODECOMMIT
        Location: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/endgameviable-content

  buildJson:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole:
        Fn::GetAtt:
          - buildRole
          - Arn
      Artifacts:
        Type: S3
        Location:
          Ref: artifactBucket
      Environment:
        Type: ARM_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        EnvironmentVariables:
          - Name: EGV_RESOURCE_MARKDOWN_BUCKET
            Value:
              Ref: markdownBucket
          - Name: EGV_RESOURCE_JSON_BUCKET
            Value:
              Ref: jsonBucket
      Source:
        Type: GITHUB
        Location: https://github.com/endgameviable/endgameviable-json

  buildDatabase:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole:
        Fn::GetAtt:
          - buildRole
          - Arn
      Artifacts:
        Type: S3
        Location:
          Ref: artifactBucket
      Environment:
        Type: ARM_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-aarch64-standard:3.0
        EnvironmentVariables:
          - Name: EGV_RESOURCE_JSON_BUCKET
            Value:
              Ref: jsonBucket
          - Name: EGV_RESOURCE_SEARCH_TABLE
            Value:
              Ref: searchTable
      Source:
        Type: GITHUB
        Location: https://github.com/endgameviable/endgameviable-dbsync

  buildNotification:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: buildPipelineStageNotificationRule
      DetailType: BASIC
      Resource:
        Fn::Sub: arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${buildPipeline}
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-started
        - codepipeline-pipeline-stage-execution-started
        - codepipeline-pipeline-stage-execution-succeeded
        - codepipeline-pipeline-stage-execution-failed
      Targets:
        - TargetType: SNS
          TargetAddress:
            Ref: buildTopic

Outputs:
  ContentBucket:
    Description: S3 bucket containing JSON data for the blog
    Value:
      Ref: markdownBucket
  JSONBucket:
    Description: S3 bucket containing JSON data for the blog
    Value:
      Ref: jsonBucket
  SearchTable:
    Description: Dynamo table for search queries
    Value:
      Ref: searchTable
  StateTable:
    Description: Dynamo table for metadata
    Value:
      Ref: stateTable
